language: python
env:
  - REQUIREMENTS=true
  - REQUIREMENTS=false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.4"
# command to install dependencies
install:
  - if [[ $REQUIREMENTS == true ]] ; then pip install -r requirements.txt ; fi
  - pip install coveralls pytest pytest-cov coverage codecov
  - pip install -e .
  - if [[ ! $TRAVIS_PYTHON_VERSION == 'pypy-5.4' ]] ; then pip install regex; fi
# command to run tests
script: py.test
sudo: false
after_success:
  - coveralls
  - codecov
