dist: xenial   # required for Python >= 3.7
language: python
env:
  - REQUIREMENTS=true
  - REQUIREMENTS=false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - if [[ $REQUIREMENTS == true ]] ; then pip install -r requirements.txt ; fi
  - pip install -U coveralls pytest pytest-cov coverage codecov
  - pip install -e .
  - if [[ ! $TRAVIS_PYTHON_VERSION == 'pypy-5.4' ]] ; then pip install regex; fi
# command to run tests
script: py.test
after_success:
  - coveralls
  - codecov
